### ISSUE TITLE
Prevent the plugin from breaking when config is empty

### ISSUE THREAD

**Issue by hacknug** [generoi/tailwindcss-gutenberg#5]
Plugin should either:
- Use default values (maybe pull them from the default config although this is opinionated and might also introduce new issues when dealing with values missing from a project's config)
- Pass a default value to all `theme()` calls

I think the second option will be better.

Again, let me know if you'd like me to open a PR fixing this 👍

**Comment by oxyc** [comment]
I'd rather pass default values than pulling them from the config. There's a few values where we could use WordPress default values I think but it's a bit annoying finding those...

Any PR that fixes the plugin breaking when config is empty is much appreciated 👍
