### ISSUE TITLE
Adding to Wordpress

### ISSUE THREAD

**Issue by 7Ds7** [generoi/tailwindcss-gutenberg#8]
I am a little confused here, and sorry if this is not the right place to ask.

I have created blocks with https://github.com/ahmadawais/create-guten-block and added them to my theme/plugin although in this repo i only see javascript files and am kind of lost on how to include it on my theme/plugin etc...

Any hints on how to do it?

**Comment by silentnoodlemaster** [comment]
This is a plugin for [Tailwind CSS](https://tailwindcss.com/)
